# Docker Compose file Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.9'

services:
  # fastapi:
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   container_name: ${CONTAINER_NAME_API}
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./.env

  fastapi:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    # volumes:
      # - .:/code
    # environment:
    #   - MODULE_NAME=app.main
    #   - VARIABLE_NAME=app
    #   - WORKERS_PER_CORE=1
    #   - WEB_CONCURRENCY=1
    # command: uvicorn main:app --host 0.0.0.0 --port

  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER: postgres
  #     - POSTGRES_PASSWORD: password
  #     - POSTGRES_DB: bandim
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432

  # redis:
  #   restart: always
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - 6379:6379

networks:
  default:
    name: backend