# Docker Compose file Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.9'

services:
  # fastapi:
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   container_name: ${CONTAINER_NAME_API}
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./.env

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: password
      - POSTGRES_DB: bandim
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

networks:
  default:
    name: backend